### ISSUE TITLE
Veranstaltung: INTERLIS-Anwender:innen-Treffen 6.11. 

### ISSUE THREAD

**Issue by zigertiger** [geostandards-ch/website-interlis-ch#7]
Bitte unter Veranstaltungen folgenden Eintrag aufnehmen:

4e Rencontre des utilisateurs INTERLIS / 4. INTERLIS-Anwender:innen-Treffen
Mittwoch, 6. November 2024, HEIG-VD, Rue St-Roch 20, Yverdon-les-Bains
https://interlis.discourse.group/t/4e-rencontre-des-utilisateur-rices-interlis-4-interlis-anwender-innen-treffen/310

Merci+Gruss, Peter Staub

**Comment by beistehen** [comment]
leider obsolet
